### ISSUE TITLE
Ctdnn approach dount

### ISSUE THREAD

**Issue by mihirp1998** [vzxxbacq/speaker-recognition-papers#2]
Hi Fang,

Thanks for implementing these research papers.Means a lot.

Would want to know what does 9,40,1 represent in this line of code
How can i use mfcc feature extractor to create this array. 

`tf.placeholder(tf.float32, shape=[None, 9, 40, 1], name='pred_x')`

Thanks

**Comment by vzxxbacq** [comment]
Hi Mihir, I'm glad to know my work is useful to you~

In this paper, authors use 40-d Fbank feature and concatenate 4 frames' feature before and after each frame. It's easy to implement, you just need to write code like this ` 
feature[index] = feature[index-4 : index+5]`. So, the features' shape is (9, 40) and the 1 represents channel.

If you want use MFCC feature, you can use 40-d MFCC feature or change 40 to 39, but you need also to modify the conv_kernel and stride.

**Comment by mihirp1998** [comment]
Hi Fang,

Sorry for the late mail buddy. Thanks for the mail, i even noticed it on
the paper a bit later about the dimensions. I'm currently training the
ctdnn model over 500 speakers each 1 hr data. I'll soon be forking ur
project and would be adding a pretrained model for 500 speaker, and also
will add i-vector plda, jfa and wccn and svm approach (mainly latent
variable statistical models ) in which i have made some modification
referring to the recent research papers which seems to give me the best
results for speaker identification. Along with some gui and vad that i have
made.

Let me know if you have anything anything better to work on in speaker
identification. Thanks.

**Comment by mihirp1998** [comment]
Thanks a lot

**Comment by vzxxbacq** [comment]
@mihirp1998 I saw the email you sent me, but I didn't see the reply here, so weird.

I glad to know my repo is useful to you, and I also hope you would like to pull request after implemented them. If you have any questions about my code, feel free to contact me.

About the work on SV. Recently I am studying the effect of data augmentation (e.g. add noise) on the speaker recognition model. Although I have not made much progress now, I think this is feasible.

**Comment by mihirp1998** [comment]
nice to hear that. I'm currently working with a team of 3 .. we r working on noise cancellation techniques rather, like ltsd and few other. We will soon commit it to ur repo. Haven't really looked into noise augmentation. Can u share me some relevant links about it.

**Comment by vzxxbacq** [comment]
@mihirp1998 
Thanks for your contribution so much.
This is link to [data aug paper](https://www.danielpovey.com/files/2018_icassp_xvectors.pdf).
