### ISSUE TITLE
Using DataManage4BigData class

### ISSUE THREAD

**Issue by pranoot** [vzxxbacq/speaker-recognition-papers#7]
Hello @vzxxbacq ,

I wanted to use the class DataManage4BigData but am stuck with few queries. I have listed them down so can you please help me with the same?

1. There is a parameter 'split_type' for the class, what should be its value? Should it be 'train' or 'validation' depending upon the types of clips we are using ?
2. There is a write-file method in it which uses the extracted features but since my dataset is huge its showing me Memory Error for once i extract features for whole dataset. I wanted to know is there anything I am doing wrong in the process for training using large dataset?

Thank you for your help! :)

**Comment by vzxxbacq** [comment]
Hi, @pranoot .

The 'split_type' is used for storing different part of your data like train, test, and they will be stored in save_path/data/split_type.
And I'm sorry I didn't apply the method to handle this situation, but it's not difficult to implement. I can rewrite `write_file` in several days.

**Comment by pranoot** [comment]
Hey Thank you for the revert. Ok I'll write the script and try to implement it. Just wanted to check if I was doing anything wrong.

**Comment by vzxxbacq** [comment]
Hello @pranoot , I changed the code that allow us to write dataset in several steps, now we can write a script to save different parts of dataset the datamanger will be auto reloaded ( the path in the config should be the same. ), and you can also use clear() method to delete saved file. A simple example in the `deep_speaker.py`.

**Comment by vzxxbacq** [comment]
If you still have questions, feel free to reopen it~

**Comment by pranoot** [comment]
Hii,
I am running the script and its giving me this error.
``` 
RuntimeWarning: invalid value encountered in float_scalars
  return np.dot(vector1, vector2) / (np.linalg.norm(vector1) * (np.linalg.norm(vector2)))
```
Can you please help me withthe same?
The error is in the cosine function.

Thank you !
