### ISSUE TITLE
Validation Accuracy low for Deep Speaker Model

### ISSUE THREAD

**Issue by pranoot** [vzxxbacq/speaker-recognition-papers#8]
Hi @vzxxbacq 

I have been trying to train my model for 18 speakers but the validation accuracy is really low and I have tried it for various different architecture but the training as well as validatoin accuracy is low as well as model is not converging well. Can youplease help me out and tell me what is going wrong ?

Thank you

**Comment by vzxxbacq** [comment]
@pranoot I'm very sorry for my late reply, and I have fixed some bugs of my structure hope it will be helpful.
